package ru.eremin.tm.server.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-05-07T18:23:21.755+03:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "AccessForbiddenException", targetNamespace = "http://endpoint.server.tm.eremin.ru/")
public class AccessForbiddenException_Exception extends java.lang.Exception {

    private ru.eremin.tm.server.endpoint.AccessForbiddenException accessForbiddenException;

    public AccessForbiddenException_Exception() {
        super();
    }

    public AccessForbiddenException_Exception(String message) {
        super(message);
    }

    public AccessForbiddenException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AccessForbiddenException_Exception(String message, ru.eremin.tm.server.endpoint.AccessForbiddenException accessForbiddenException) {
        super(message);
        this.accessForbiddenException = accessForbiddenException;
    }

    public AccessForbiddenException_Exception(String message, ru.eremin.tm.server.endpoint.AccessForbiddenException accessForbiddenException, java.lang.Throwable cause) {
        super(message, cause);
        this.accessForbiddenException = accessForbiddenException;
    }

    public ru.eremin.tm.server.endpoint.AccessForbiddenException getFaultInfo() {
        return this.accessForbiddenException;
    }
}
