package ru.eremin.tm.server.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-22T16:26:26.056+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.server.tm.eremin.ru/", name = "AuthorizationEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface AuthorizationEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/AuthorizationEndpoint/logoutRequest", output = "http://endpoint.server.tm.eremin.ru/AuthorizationEndpoint/logoutResponse", fault = {@FaultAction(className = SessionValidateExeption_Exception.class, value = "http://endpoint.server.tm.eremin.ru/AuthorizationEndpoint/logout/Fault/SessionValidateExeption"), @FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/AuthorizationEndpoint/logout/Fault/IncorrectDataException")})
    @RequestWrapper(localName = "logout", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.LogoutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.eremin.tm.server.endpoint.ResultDTO logout(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.eremin.tm.server.endpoint.SessionDTO arg0
    ) throws SessionValidateExeption_Exception, IncorrectDataException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/AuthorizationEndpoint/loginRequest", output = "http://endpoint.server.tm.eremin.ru/AuthorizationEndpoint/loginResponse")
    @RequestWrapper(localName = "login", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.eremin.tm.server.endpoint.SessionDTO login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
