package ru.eremin.tm.server.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-04-30T17:33:09.660+03:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "IncorrectDataException", targetNamespace = "http://endpoint.server.tm.eremin.ru/")
public class IncorrectDataException_Exception extends java.lang.Exception {

    private ru.eremin.tm.server.endpoint.IncorrectDataException incorrectDataException;

    public IncorrectDataException_Exception() {
        super();
    }

    public IncorrectDataException_Exception(String message) {
        super(message);
    }

    public IncorrectDataException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IncorrectDataException_Exception(String message, ru.eremin.tm.server.endpoint.IncorrectDataException incorrectDataException) {
        super(message);
        this.incorrectDataException = incorrectDataException;
    }

    public IncorrectDataException_Exception(String message, ru.eremin.tm.server.endpoint.IncorrectDataException incorrectDataException, java.lang.Throwable cause) {
        super(message, cause);
        this.incorrectDataException = incorrectDataException;
    }

    public ru.eremin.tm.server.endpoint.IncorrectDataException getFaultInfo() {
        return this.incorrectDataException;
    }
}
