package ru.eremin.tm.server.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-22T16:26:26.320+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://endpoint.server.tm.eremin.ru/", name = "ProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/removeProjectRequest", output = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/removeProjectResponse", fault = {@FaultAction(className = SessionValidateExeption_Exception.class, value = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/removeProject/Fault/SessionValidateExeption"), @FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/removeProject/Fault/IncorrectDataException")})
    @RequestWrapper(localName = "removeProject", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.RemoveProject")
    @ResponseWrapper(localName = "removeProjectResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.RemoveProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.eremin.tm.server.endpoint.ResultDTO removeProject(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.eremin.tm.server.endpoint.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws SessionValidateExeption_Exception, IncorrectDataException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/findAllProjectsRequest", output = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/findAllProjectsResponse", fault = {@FaultAction(className = SessionValidateExeption_Exception.class, value = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/findAllProjects/Fault/SessionValidateExeption")})
    @RequestWrapper(localName = "findAllProjects", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindAllProjects")
    @ResponseWrapper(localName = "findAllProjectsResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindAllProjectsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.eremin.tm.server.endpoint.ProjectDTO> findAllProjects(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.eremin.tm.server.endpoint.SessionDTO arg0
    ) throws SessionValidateExeption_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/persistProjectRequest", output = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/persistProjectResponse", fault = {@FaultAction(className = SessionValidateExeption_Exception.class, value = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/persistProject/Fault/SessionValidateExeption")})
    @RequestWrapper(localName = "persistProject", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.PersistProject")
    @ResponseWrapper(localName = "persistProjectResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.PersistProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.eremin.tm.server.endpoint.ResultDTO persistProject(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.eremin.tm.server.endpoint.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ru.eremin.tm.server.endpoint.ProjectDTO arg1
    ) throws SessionValidateExeption_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/findOneProjectRequest", output = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/findOneProjectResponse", fault = {@FaultAction(className = SessionValidateExeption_Exception.class, value = "http://endpoint.server.tm.eremin.ru/ProjectEndpoint/findOneProject/Fault/SessionValidateExeption")})
    @RequestWrapper(localName = "findOneProject", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindOneProject")
    @ResponseWrapper(localName = "findOneProjectResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindOneProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.eremin.tm.server.endpoint.ProjectDTO findOneProject(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.eremin.tm.server.endpoint.SessionDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws SessionValidateExeption_Exception;
}
