package ru.eremin.tm.server.endpoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-05-08T18:07:28.993+03:00
 * Generated source version: 3.2.3
 */
@WebServiceClient(name = "ServerEndpointService",
        wsdlLocation = "http://localhost:80/ServerEndpoint?WSDL",
        targetNamespace = "http://endpoint.server.tm.eremin.ru/")
public class ServerEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.server.tm.eremin.ru/", "ServerEndpointService");
    public final static QName ServerEndpointPort = new QName("http://endpoint.server.tm.eremin.ru/", "ServerEndpointPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:80/ServerEndpoint?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServerEndpointService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:80/ServerEndpoint?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ServerEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServerEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServerEndpointService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServerEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServerEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns ServerEndpoint
     */
    @WebEndpoint(name = "ServerEndpointPort")
    public ServerEndpoint getServerEndpointPort() {
        return super.getPort(ServerEndpointPort, ServerEndpoint.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ServerEndpoint
     */
    @WebEndpoint(name = "ServerEndpointPort")
    public ServerEndpoint getServerEndpointPort(WebServiceFeature... features) {
        return super.getPort(ServerEndpointPort, ServerEndpoint.class, features);
    }

}
