package ru.eremin.tm.server.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-05-08T18:07:28.990+03:00
 * Generated source version: 3.2.3
 */
@WebService(targetNamespace = "http://endpoint.server.tm.eremin.ru/", name = "ServerEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ServerEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/ServerEndpoint/serverInfoRequest", output = "http://endpoint.server.tm.eremin.ru/ServerEndpoint/serverInfoResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/ServerEndpoint/serverInfo/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/ServerEndpoint/serverInfo/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "serverInfo", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.ServerInfo")
    @ResponseWrapper(localName = "serverInfoResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.ServerInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    ru.eremin.tm.server.endpoint.ServerDTO serverInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;
}
