package ru.eremin.tm.server.endpoint;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-04-22T16:26:26.451+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "SessionValidateExeption", targetNamespace = "http://endpoint.server.tm.eremin.ru/")
public class SessionValidateExeption_Exception extends java.lang.Exception {

    private ru.eremin.tm.server.endpoint.SessionValidateExeption sessionValidateExeption;

    public SessionValidateExeption_Exception() {
        super();
    }

    public SessionValidateExeption_Exception(String message) {
        super(message);
    }

    public SessionValidateExeption_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SessionValidateExeption_Exception(String message, ru.eremin.tm.server.endpoint.SessionValidateExeption sessionValidateExeption) {
        super(message);
        this.sessionValidateExeption = sessionValidateExeption;
    }

    public SessionValidateExeption_Exception(String message, ru.eremin.tm.server.endpoint.SessionValidateExeption sessionValidateExeption, java.lang.Throwable cause) {
        super(message, cause);
        this.sessionValidateExeption = sessionValidateExeption;
    }

    public ru.eremin.tm.server.endpoint.SessionValidateExeption getFaultInfo() {
        return this.sessionValidateExeption;
    }
}
