package ru.eremin.tm.server.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2019-05-07T18:23:21.583+03:00
 * Generated source version: 3.2.3
 */
@WebService(targetNamespace = "http://endpoint.server.tm.eremin.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findAllUsersRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findAllUsersResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findAllUsers/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findAllUsers/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindAllUsers")
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindAllUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    java.util.List<ru.eremin.tm.server.endpoint.UserDTO> findAllUsers(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/updateUserRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/updateUserResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/updateUser/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/updateUser/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.UpdateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    ru.eremin.tm.server.endpoint.ResultDTO updateUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.UserDTO arg1
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUserRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUserResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUser/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUser/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "findOneUser", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindOneUser")
    @ResponseWrapper(localName = "findOneUserResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindOneUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    ru.eremin.tm.server.endpoint.UserDTO findOneUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/persistUserRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/persistUserResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/persistUser/Fault/IncorrectDataException")})
    @RequestWrapper(localName = "persistUser", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.PersistUser")
    @ResponseWrapper(localName = "persistUserResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.PersistUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    ru.eremin.tm.server.endpoint.ResultDTO persistUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.UserDTO arg0
    ) throws IncorrectDataException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/changeUserPasswordRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/changeUserPasswordResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/changeUserPassword/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/changeUserPassword/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.ChangeUserPasswordResponse")
    @WebResult(name = "return", targetNamespace = "")
    ru.eremin.tm.server.endpoint.ResultDTO changeUserPassword(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    java.lang.String arg2
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/sessionValidateRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/sessionValidateResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/sessionValidate/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/sessionValidate/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "sessionValidate", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.SessionValidate")
    @ResponseWrapper(localName = "sessionValidateResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.SessionValidateResponse")
    void sessionValidate(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/removeUserRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/removeUserResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/removeUser/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/removeUser/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.RemoveUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    ru.eremin.tm.server.endpoint.ResultDTO removeUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;

    @WebMethod
    @Action(input = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUserByLoginRequest", output = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUserByLoginResponse", fault = {@FaultAction(className = IncorrectDataException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUserByLogin/Fault/IncorrectDataException"), @FaultAction(className = AccessForbiddenException_Exception.class, value = "http://endpoint.server.tm.eremin.ru/UserEndpoint/findOneUserByLogin/Fault/AccessForbiddenException")})
    @RequestWrapper(localName = "findOneUserByLogin", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindOneUserByLogin")
    @ResponseWrapper(localName = "findOneUserByLoginResponse", targetNamespace = "http://endpoint.server.tm.eremin.ru/", className = "ru.eremin.tm.server.endpoint.FindOneUserByLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    ru.eremin.tm.server.endpoint.UserDTO findOneUserByLogin(
            @WebParam(name = "arg0", targetNamespace = "")
                    ru.eremin.tm.server.endpoint.SessionDTO arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    ) throws IncorrectDataException_Exception, AccessForbiddenException_Exception;
}
